// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define ID_FILE_NEW 0xE100 
#define ID_FILE_OPEN 0xE101 
#define ID_FILE_CLOSE 0xE102 
#define ID_FILE_SAVE 0xE103 
#define ID_FILE_SAVE_AS 0xE104 
#define ID_FILE_PAGE_SETUP 0xE105 
#define ID_FILE_PRINT_SETUP 0xE106 
#define ID_FILE_PRINT 0xE107 
#define ID_FILE_PRINT_DIRECT 0xE108 
#define ID_FILE_PRINT_PREVIEW 0xE109 
#define ID_EDIT_COPY 0xE122 
#define ID_EDIT_CUT 0xE123 
#define ID_EDIT_FIND 0xE124 
#define ID_EDIT_PASTE 0xE125 
#define ID_EDIT_SELECT_ALL 0xE12A 
#define ID_EDIT_UNDO 0xE12B 
#define ID_EDIT_REDO 0xE12C 
#define ID_WINDOW_NEW 0xE130 
#define ID_WINDOW_SPLIT 0xE135 
#define ID_APP_ABOUT 0xE140 
#define ID_APP_EXIT 0xE141 
#define ID_NEXT_PANE 0xE150 
#define ID_PREV_PANE 0xE151 
#define ID_PANE_CLOSE 0xE152 
#define ID_VIEW_TOOLBAR 0xE800 
#define ID_VIEW_STATUS_BAR 0xE801 
#define ID_VIEW_RIBBON 0xE804 
#define ID_BTN_RESET 2 
#define ID_BTN_RESET_LabelTitle_RESID 60001
#define ID_BTN_RESET_TooltipTitle_RESID 60002
#define ID_BTN_RESET_TooltipDescription_RESID 60003
#define ID_BTN_RESET_LargeImages_RESID 60004
#define ID_BTN_SELECT 3 
#define ID_BTN_SELECT_LabelTitle_RESID 60005
#define ID_BTN_SELECT_TooltipTitle_RESID 60006
#define ID_BTN_SELECT_TooltipDescription_RESID 60007
#define ID_BTN_SELECT_LargeImages_RESID 60008
#define ID_BTN_NEW 4 
#define ID_BTN_NEW_LabelTitle_RESID 60009
#define ID_BTN_NEW_TooltipTitle_RESID 60010
#define ID_BTN_NEW_TooltipDescription_RESID 60011
#define ID_BTN_NEW_LargeImages_RESID 60012
#define ID_BTN_EDIT 5 
#define ID_BTN_EDIT_LabelTitle_RESID 60013
#define ID_BTN_EDIT_TooltipTitle_RESID 60014
#define ID_BTN_EDIT_TooltipDescription_RESID 60015
#define ID_BTN_EDIT_LargeImages_RESID 60016
#define ID_BTN_DELETE 6 
#define ID_BTN_DELETE_LabelTitle_RESID 60017
#define ID_BTN_DELETE_TooltipTitle_RESID 60018
#define ID_BTN_DELETE_TooltipDescription_RESID 60019
#define ID_BTN_DELETE_SmallImages_RESID 60020
#define ID_BTN_CLEAN_UP 7 
#define ID_BTN_CLEAN_UP_LabelTitle_RESID 60021
#define ID_BTN_CLEAN_UP_TooltipTitle_RESID 60022
#define ID_BTN_CLEAN_UP_TooltipDescription_RESID 60023
#define ID_BTN_CLEAN_UP_SmallImages_RESID 60024
#define ID_BTN_CODE 8 
#define ID_BTN_CODE_LabelTitle_RESID 60025
#define ID_BTN_CODE_TooltipTitle_RESID 60026
#define ID_BTN_CODE_TooltipDescription_RESID 60027
#define ID_BTN_CODE_SmallImages_RESID 60028
#define ID_BTN_GENERATE 9 
#define ID_BTN_GENERATE_LabelTitle_RESID 60029
#define ID_BTN_GENERATE_TooltipTitle_RESID 60030
#define ID_BTN_GENERATE_TooltipDescription_RESID 60031
#define ID_BTN_GENERATE_LargeImages_RESID 60032
#define ID_BTN_HEADER 10 
#define ID_BTN_HEADER_LabelTitle_RESID 60033
#define ID_BTN_HEADER_TooltipTitle_RESID 60034
#define ID_BTN_HEADER_TooltipDescription_RESID 60035
#define ID_BTN_HEADER_SmallImages_RESID 60036
#define ID_BTN_FOOTER 11 
#define ID_BTN_FOOTER_LabelTitle_RESID 60037
#define ID_BTN_FOOTER_TooltipTitle_RESID 60038
#define ID_BTN_FOOTER_TooltipDescription_RESID 60039
#define ID_BTN_FOOTER_SmallImages_RESID 60040
#define ID_BTN_TYPEDEF 12 
#define ID_BTN_TYPEDEF_LabelTitle_RESID 60041
#define ID_BTN_TYPEDEF_TooltipTitle_RESID 60042
#define ID_BTN_TYPEDEF_TooltipDescription_RESID 60043
#define ID_BTN_TYPEDEF_SmallImages_RESID 60044
#define ID_BTN_NOTES 13 
#define ID_BTN_NOTES_LabelTitle_RESID 60045
#define ID_BTN_NOTES_TooltipTitle_RESID 60046
#define ID_BTN_NOTES_TooltipDescription_RESID 60047
#define ID_BTN_NOTES_LargeImages_RESID 60048
#define ID_BTN_SEARCH 14 
#define ID_BTN_SEARCH_LabelTitle_RESID 60049
#define ID_BTN_SEARCH_TooltipTitle_RESID 60050
#define ID_BTN_SEARCH_TooltipDescription_RESID 60051
#define ID_BTN_SEARCH_LargeImages_RESID 60052
#define ID_BTN_CONSOLE 15 
#define ID_BTN_CONSOLE_LabelTitle_RESID 60053
#define ID_BTN_CONSOLE_TooltipTitle_RESID 60054
#define ID_BTN_CONSOLE_TooltipDescription_RESID 60055
#define ID_BTN_CONSOLE_LargeImages_RESID 60056
#define ID_BTN_MODULES 16 
#define ID_BTN_MODULES_LabelTitle_RESID 60057
#define ID_BTN_MODULES_TooltipTitle_RESID 60058
#define ID_BTN_MODULES_TooltipDescription_RESID 60059
#define ID_BTN_MODULES_LargeImages_RESID 60060
#define ID_TAB_HOME 17 
#define ID_TAB_HOME_LabelTitle_RESID 60061
#define ID_TAB_MODIFY 18 
#define ID_TAB_MODIFY_LabelTitle_RESID 60062
#define ID_TAB_SETTINGS 19 
#define ID_TAB_SETTINGS_LabelTitle_RESID 60063
#define ID_GROUP_PROJECT 20 
#define ID_GROUP_PROJECT_LabelTitle_RESID 60064
#define ID_GROUP_DRIVER 21 
#define ID_GROUP_DRIVER_LabelTitle_RESID 60065
#define ID_GROUP_CLASS 22 
#define ID_GROUP_CLASS_LabelTitle_RESID 60066
#define ID_GROUP_CODE 23 
#define ID_GROUP_CODE_LabelTitle_RESID 60067
#define ID_GROUP_TOOLS 24 
#define ID_GROUP_TOOLS_LabelTitle_RESID 60068
#define ID_RIBBON_APP_MENU 25 
#define ID_SAVEMORE 26 
#define ID_PRINTMORE 27 
#define ID_RIBBON_QAT 28 
